#pragma config(Sensor, dgtl1,  bump1,          sensorTouch)
#pragma config(Sensor, dgtl2,  bump2,          sensorTouch)
#pragma config(Sensor, dgtl3,  flap1,          sensorTouch)
#pragma config(Sensor, dgtl4,  sonarInput,     sensorSONAR_inch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
/*
motor[port1] = 127;
motor[port3] = 127;
motor[port10] = 127;
motor[port2] = 127;
//motor[port3] = 127;
// startMotor(10, 127);
waitInMilliseconds(3000);*/

/*
motor[port1] = 30;
untilTouch(1);
untilTouch(2);
untilBump(1, 100);
untilBump(2, 100);*/

/*
// long-distance sensor
while(true)
{
	motor[port10] = 30;
	if (SensorValue(sonarInput) < 5)
	{
		motor[port10] = 0;
	}
}*/

/*
// button/flap sensors applicable
while(true)
{
	if (SensorValue(flap1) == 1)
	{
		motor[port10] = 30;
	}
	if (SensorValue(flap1) == 0)
	{
		motor[port10] = 0;
	}
}*/

//untilTouch(4);
//stop();

/*
if (SensorValue(bump1) == 0)
{
	motor[port1] = 30;
	waitInMilliseconds(3000);
}*/


	/*if (SensorValue(bump1) == 1)
	{
		motor[port1] = 0;
	}
	if (SensorValue(bump1) == 0)
	{
		motor[port1] = -30;
	}*/




// constant speed
while(true)
{
	motor[port9] = 127;
	motor[port1] = 127;
}


/*
int speed = 0;

while (true)
// program 2
{
	while (speed < 128)
	// exits the loop if the max speed is achieved
	// program 1
	{
		motor[port1] = speed;
		//motor[port10] = speed;
		waitInMilliseconds(1000);
		speed += 20;
	}
	speed = 127;
	while (speed > -128)
	// exits the loop if the max speed is achieved
	{
		motor[port1] = speed;
		//motor[port10] = speed;
		waitInMilliseconds(1000);
		speed -= 20;
	}
	speed = -127
}*/


}
