#pragma config(Sensor, dgtl1,  bump1,          sensorTouch)
#pragma config(Sensor, dgtl2,  bump2,          sensorTouch)
#pragma config(Sensor, dgtl3,  flap1,          sensorTouch)
#pragma config(Sensor, dgtl4,  sonarInput,     sensorSONAR_inch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

/*	int threshold = 10; // create and set variable 'threshold' to 10 (will be distance for sonarSensor)
	motor[port1]=100;
	motor[port10]=-100;
	wait1Msec(5000);

	while(SensorValue(sonarInput) > 90){
		motor[port1]=100;
		motor[port10]=100;
	}

	wait1Msec(130);
	motor[port1] = 10;
	motor[port10] = 10;

	while(SensorValue(sonarInput) > threshold || SensorValue(sonarInput) == -1)   // while the sonarSensor sensor is reading in values larger than our
	{                                                                   // threshold, or reading out of range (-1 = no object in sight)
		motor[port1] = 75;   // set port2 to speed 75
		motor[port10] = -75;   // set port3 to speed 75
	}
	wait1Msec(100);                            // stop the robot:
	motor[port1] = 0;      // set port2 to speed 0
	motor[port10] = 0;      // set port3 to speed 0
*/	
	
/*
motor[port1] = 127;
motor[port3] = 127;
motor[port10] = 127;
motor[port2] = 127;
//motor[port3] = 127;
// startMotor(10, 127);
waitInMilliseconds(3000);*/

/*
motor[port1] = 30;
untilTouch(1);
untilTouch(2);
untilBump(1, 100);
untilBump(2, 100);*/

/*
// long-distance sensor
while(true)
{
	motor[port10] = 30;
	if (SensorValue(sonarInput) < 5)
	{
		motor[port10] = 0;
	}
}*/

/*
// button/flap sensors applicable
while(true)
{
	if (SensorValue(flap1) == 1)
	{
		motor[port10] = 30;
	}
	if (SensorValue(flap1) == 0)
	{
		motor[port10] = 0;
	}
}*/

//untilTouch(4);
//stop();

/*
if (SensorValue(bump1) == 0)
{
	motor[port1] = 30;
	waitInMilliseconds(3000);
}*/


	/*if (SensorValue(bump1) == 1)
	{
		motor[port1] = 0;
	}
	if (SensorValue(bump1) == 0)
	{
		motor[port1] = -30;
	}*/




// constant speed
while(true)
{
	motor[port9] = 127;
	motor[port1] = 127;
}


/*
int speed = 0;

while (true)
// program 2
{
	while (speed < 128)
	// exits the loop if the max speed is achieved
	// program 1
	{
		motor[port1] = speed;
		//motor[port10] = speed;
		waitInMilliseconds(1000);
		speed += 20;
	}
	speed = 127;
	while (speed > -128)
	// exits the loop if the max speed is achieved
	{
		motor[port1] = speed;
		//motor[port10] = speed;
		waitInMilliseconds(1000);
		speed -= 20;
	}
	speed = -127
}*/


}
